FROM node:latest as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build:ssr


# Étape 2: Préparer les fichiers pour le serveur Node.js et Nginx
FROM node:latest as prepare

# Copier les fichiers nécessaires depuis le builder
COPY --from=builder /app/dist/hatypikhouse-front/server /app/server
COPY --from=builder /app/dist/hatypikhouse-front/browser /app/browser

# Étape 3: Configurer l'Image Finale avec Nginx et le Serveur Node.js
FROM nginx:latest

RUN apt-get update && apt-get install -y nodejs

# Copier les fichiers du serveur Node.js
# COPY --from=builder /app/dist/hatypikhouse-front/ /usr/share/nginx/html
COPY --from=prepare /app/server /app/server

# Copier les fichiers statiques pour Nginx
COPY --from=prepare /app/browser /usr/share/nginx/html

# Copier également les fichiers statiques pour le serveur Node.js selon le chemin attendu
COPY --from=prepare /app/browser /dist/hatypikhouse-front/browser

COPY nginx.conf /etc/nginx/nginx.conf

COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 80 4000
CMD ["/start.sh"]