export const HOUSE_CONST = {
  wording: {
    titleList: 'Toutes les maisons',
    listButton: 'Liste des maisons',
  },
  forms: {
    libelle: 'libelle',
    labelLibelle: 'Nom de la maison',
    description: 'description',
    labelDescription: 'Description',
    bedroom: 'bedroom_number',
    labelBedroom: 'Nombre de lit',
    person: 'person_number',
    labelPerson: 'Nombre de personne',
    parking: 'parking_distance',
    labelParking: 'Distance de parking',
    area: 'area',
    labelArea: 'Superficie',
    show: 'show',
    labelShow: 'Visible',
    water: 'water',
    labelWater: 'Eau',
    power: 'power',
    labelPower: 'Lumière',
    price: 'price',
    labelPrice: 'Prix',
    longitude: 'longitude',
    latitude: 'latitude',
    labelLongitude: 'Longitude',
    labelLatitude: 'latitude',
    address: 'address',
    labelAddress: 'Adresse',
    category: 'category',
    labelCategory: 'Liste des catégories',
    labelThematic: 'Liste des thematiques',
    thematic: 'thematic',
  }
}
